#Example Makefile for the apsp benchmark running with the Graphite Simulator

TARGET := apsp
OBJECTS := $(TARGET).o

THREADS ?= 8
SIZE ?= 16384
DEGREE ?= 16
APP_FLAGS ?= $(THREADS) $(SIZE) $(DEGREE)

include ../../Makefile.tests
